### PR TITLE
Paint state modifier 

### LINKED ISSUE #291: Paint state modifiers based on state
It is a bit hard to gauge if a state modifier (such as keep-walking) is on.

A simple method is to count the number of them, perhaps during script generation, and then paint the modifier green if there is an odd amount of that state among the steps.

### PR DESCRIPTION
**Pull request by theis999**
Paints never_idle, keep_walking, keep_on_path & keep_crafting green. 
When there is an uneven amount of those steps, to indicate it is turned on.

### CODE REVIEW

**Review by MortenTobiasNielsen — CHANGES_REQUESTED** [review]
This implementation can be a little misleading/confusing, given that it doesn't know where in the grid I am. I might be doing something at step 13K out of 30K and the marker being green is telling me that at the end of the 30K it will be on, but not what it is at the 13K. 

Is it possible to mark it the same way we mark e.g. Diagonal?

**Comment by theis999** [comment]
I understand what you mean, but I think it will be a very infrequent issue. Most of the time people won't go far back in step list to modify these types of steps. Since they mostly matter for active development.

Anyway, i will try just because i like having more colour in the GUI.

**Comment by theis999** [comment]
Done

**Review by MortenTobiasNielsen — APPROVED** [review]
It would be nice if the steps were colored immediately instead of only being done when the script is generated, but we can have a look at that at a later time. :)

**Pull request merged**
